server:
  port: 8081

spring:
  application:
    name: config-service
  kafka:
    bootstrap-servers: ${KAFKA_CLUSTER01:15.164.103.31:9092}

  cloud:
    bus:
      enabled: true

    config:
      server:
        git:
          uri: git@github.com:134talk/backend_config.git
          default-label: main
          private-key: ENC(qyu0cFG7+SjogvNHiC4Ka+tQYDygJ8V7wf+C2y2CatbC+Nrqv7H0dvML1PnvuNptaakkdNkyFCsHZmqIUkeNsz0hZSJEXzA0ceWX9GCD34KzSWmzRp6pQKe7gYC3+AUrKnqRIwSTHvpE7+WXa2DI4su7p5UVeFaZMHCTWvZq3hO2GSeimN4Bw0TQLtcZ2x9Q49DEpte6X9Z4pS+1nFjlPN8p9j0dO/5c+Uvvg9/IXQiDIXFgiceIxscfjZcZGiTv6OI61RfmPAGXNNj7FOdX7kZbNCXCgc0CBH83r8BpmlAeka7HUBX/7GbKyr2ufa3KvKWaD0UJ/ad4RPcYS33PNwsc6NcWM73COE6DRWsCZSa79JrWqmNaitnCL5gE8xgOjguj0OOsnJTNwW9LqGKMig7c9lPrpyIObkSwEAFqwrTLIkvER/avUX+crpK6Ur5i45j9/ci9NAjrS/CK9Z5ah5gF8Ds2EMeEK8Bqs1Y0hNMvvsJU9Dkc4ucXgjmrX+jRy2hHUQspWtKSagCLXFT4BDSasSuwulsWZJzmDs5lynn/xYu84GRHle4F2DV53brf0m0huWk750fXPJ8E0g6ZblVI4mbd1VQsbNxlgTuGEi3YeG/fJ8VRqbmrcbd5CsJ9MQ0ceVwM1L5m+PG8u/ZgS6TJuyuCP7ji/iPTAK7BVZQYRmfmjclWBJKJKjyU4Ed8noKvcbrMmgDlc62uCu5y5WoWFsBoeYurT3J/cQ4ua2eeXjiiuoLNBlm9XgE4L0sk/FbCwd6r7LrxYqHYxV0BFvGUzcyhzrowuQ+vEtKTbagbatqt0zcLYMM1Kte/MKeMfVX3mFUgYaYSptd6xJirLpnBWlg8ooDikeMaaaUJgPduIICtElZQ+/B2Jybw6vq9qNiElhmg1di86UR2EL3tmUkX/mEYEmLJorTAIiA4/AxsRYFbXaHUlU6j5JOf0msAx01P9cfs+RtgTW6TP/aacuPNzM+r1lP14sIGa/2b25whWYytTkTou3J3Ufp2U2JZpthx0hlAAxE9GR2bYplXcXOBKsrqLey8m7NHwT8zx5K89wKfYiN3AQdSklfmkM5k10AI/wblN86prxd4dWSuegvdkhHHiST0/Fvzyhz8APz6wYzuIVVestRJgmyVtzsNB8da7eht47MQBJVvxieskgXa3e2ITPsgLkZTEcGD103tkMNR5hOMNCcWhuhzUjU2OcqZqG/5Tw/7CnaAd9NgG2iyIjIGhtfRo0bZqdvTdw59BxVTDXsNo4iShCJLkju5OCd1uszfvM7ghwxKCdNPPDfgk37oCE3wxWzC/DUSPeDMJH1Y2FJ7Ld3J98m5CrRMLzfzNJ9PKp6e/umP6sUwIPaXJRGZmPqTlecROKcW+IAFfJvrrneS8O7wnkVY4xjEFNalplyTpy8HmivUmrk0izn1ZUwDPVxM3x5sCQa83PapGHv3M6HNXfAJpfAjMbt+/Yc4roK/mVtk/EYurDx3H7WU9+qOXqW1G7vrNd8wkYh+83ZWRLvr2x2Oa03TnmvWPR5U70p0Q0J95PJJOImUvn+tKF5PvfVKvruCs3wG+2x2vejQciWCHqz2a7il0PauCBVrP8mQ3js3TyF4b57qp11id7BD8QHsHE54gWTGatqkkPvUndtZjCpTtFMmWsd1fSUiA2umwmwUcYB27A66SfX1uhzPEhLzRAhBFaeUbQun1v0DIHrnGcV98zt+3WELltbHNdlAwB7oXPsxL1oCUH7gIKn8552wESoMWA2RUrZK2yYcFOj+uWzcA96Ro3XLXuAAMWOfbXr8LAJknKtyMdUMtheOwk08cSi8Jh8p+x50jE8DvlLh0R6AKYxjUICfr9nM/A8o0Rbix6mDO/owysPHut7htJ4gNviFIbk9m60yA+OQTvn7+Z0HYcXo8XerLnlFDJ1VVqVykbjmi4EVS7/sanIt3qmSvr82hcZ9PcijOZdZNK5Z0Ynp6A8M+FK0JjvCPZEVhBhJW3MvpO8ZfZxcrxxzBqRhq54H69HiD3Q0BGzhVqG3c2i6Id5Hj2V8e3XhnfbY83OvEYxnHvemrOdJhme4puXbYpImyTvKh4XDXgl4htXasFHPQ35fQ2CNRnV1B5LjHrjo3ecBH636yqEyMvieGRWGQmmN4is+Ucs5zkjlzuPFmyzBr+xf+95jvi8EXRu54oARxvbyz6XiTqlMKGTYgyK45ERCcg4azkp23s/5x7EBAXcZJhkrlnCfCYL2Ih9m7neTGm2jn1n4JBJIelneSQ7z78upm7lovCKMpIMOJGCjperyktGCGh7Y7c7D8jHYHU4qrGMWrNhTgowuGUdlzk1J8kx/ZH2zBPSiqjAmkVMdTBJmN7EMl4l8Eer5Pi+pY2Ownvd25cEXie6kaq1jtJ34grqrPDitQBFhOT9tdCLCwWpE9IUoDtONi4/xD19mmirv9agv6PZYky/jfWEFvSLDXs/Dx/ajTCYR0/3ysl8iZueT6d/LIhwQm4n2XVeqzmq+t8F/MCIr6zwHYldI4VDZZ30IHO2l70QwpLAjOaSbyQKWExK7H7qONRa/jwWFCD3QlQBbLzuHfW0X03SsI+9Saf2+2Cf0VLI81TQqvjcY1rLswAiK49lyLyPVfzjj/aYx3hWKX/yH7tS1WSvwxRlw6O/Ra1ylQDBv1ZAfinOV5q39ucxOZ/stOrmtbX9/ApfAY1TnFJ3HjSDmPVBvAdeVR+fFJB/gpdBA1Sp/oW3OPgMUQE6T/TMDb1kaFf396US9A8BDaw20PvLCFFMY06ZDZdgYwaNMou1vTpZkAP+kLodSIh9Y0+GwITtTI/r4l5+RYKE81dO+xRxPl3nB6C76p3+MzTRUo4raqooV1yv6CuPuyzFiFkL8/ZcskUauMeOm9q/9iT06aa5pN++skY/xjKtjYTuBWwp5mOln/H7FtijaRZmOhGR2dagmQ49hvq9QZYpWKDodWNuCOJ2bJ8YEsLd2dQ54EU9+DC7awomHgwXlWB9/V9j9C8/dw4IA8TCPSWbHS2V7e4ouzVnFoVgD+fG14w8EzaUyae2+V4C7cfky/qPLxf2NjRbZJOv7ihyVq+wGzsywrueqVVdc9JcMAWjgYpHRjm1/t0slvXUiGmqPwgeRWVnh+QYe5iavjgLCsDiKw4kMMMcSof7R72bA6OUhsBUbF0kP4qHZoLJzu8qWXHgdbb8UDG5NMpiWYBGzGHHkvN7+St/iAmCgnOX0m7qf54x9QsEhdTW5/xfLLAWftHw+2cSuO3Y475XBp4Q3K5aLYtQVXfMTcvtJRMKSKz2TGbvqhHK3R+jWygH731n1CmC5ZZzNqR96mSoIwgBPGnFG0NVjBP/t0vEty88WVFaKYk072oAcRgNhXiQbcFivQhLSwdX4FeVJraKlK7NYwHEHiaNFVyD1ZYcPIp6JHMrlkzHR6ShGgTMplIwGDg==)
          ignore-local-ssh-settings: true
        encrypt:
          enabled: false


jasypt:
  encryptor:
    bean: jasyptStringEncryptor





