server:
  port: 8081

spring:
  application:
    name: config-service
  kafka:
    bootstrap-servers: ${KAFKA_CLUSTER01:15.164.103.31:9092}

  cloud:
    bus:
      enabled: true

    config:
      server:
        git:
          uri: git@github.com:134talk/backend_config.git
          default-label: main
          private-key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAYEAmf/cs04oPmPLxqNM1kriVc41QZxrVQZWz4+l5njl6ww/EC6JDVeF
            hcNcDGUA6zk/pYyINMysS+vP2YJFFmaUWfRpgtwhCSEe+GFULhSLJaZnIVlhTs01t9h/Ah
            EGAwlcn298A/NDF9CEXNNPffqldmnwBbHmjL63JtIFkU3kT4A11ubalyzwf2fxemn0TzPc
            jPhZPvSqS38UIoSyspz0B1mGvykZki3kk2Bcsvs8ZGgmjm3Jw9TFGtL0PQviciPzXHvJAQ
            Y2mmpX1niNDBrUddpDlV0+f1AjkRB7szmV4dTNuuoUy1gyBGR3X7N0sdGhVw6ee1rDi/W2
            F1L+IHCty8sTZ3KIhELJRXZSCgx2m2YXs5sUp5CuBdfrmRM7TIUWzUe44lKfmHk6I0Vk8d
            Q5Pvd3qlnAOwRb2YFhxeO/43ARyUArjWpp8DAelPdc/+e0mOeoh9zITl/2IP/AFjUuTR4w
            JfLWz/kDU3p9K/3pNQ0pjUNIneedQZ02LBmT2YIrAAAFkKNUwsKjVMLCAAAAB3NzaC1yc2
            EAAAGBAJn/3LNOKD5jy8ajTNZK4lXONUGca1UGVs+PpeZ45esMPxAuiQ1XhYXDXAxlAOs5
            P6WMiDTMrEvrz9mCRRZmlFn0aYLcIQkhHvhhVC4UiyWmZyFZYU7NNbfYfwIRBgMJXJ9vfA
            PzQxfQhFzTT336pXZp8AWx5oy+tybSBZFN5E+ANdbm2pcs8H9n8Xpp9E8z3Iz4WT70qkt/
            FCKEsrKc9AdZhr8pGZIt5JNgXLL7PGRoJo5tycPUxRrS9D0L4nIj81x7yQEGNppqV9Z4jQ
            wa1HXaQ5VdPn9QI5EQe7M5leHUzbrqFMtYMgRkd1+zdLHRoVcOnntaw4v1thdS/iBwrcvL
            E2dyiIRCyUV2UgoMdptmF7ObFKeQrgXX65kTO0yFFs1HuOJSn5h5OiNFZPHUOT73d6pZwD
            sEW9mBYcXjv+NwEclAK41qafAwHpT3XP/ntJjnqIfcyE5f9iD/wBY1Lk0eMCXy1s/5A1N6
            fSv96TUNKY1DSJ3nnUGdNiwZk9mCKwAAAAMBAAEAAAGAGZnmh8xzdkPC6afWKz3RuLAKPH
            kTgtQF9IWN7+2jU1r61ObXk+c75Evg7pKP/4rJ4Oym7BgmgIyYRjGY6Ktu+DFgpQeRWmIu
            Mt6DTxHNPBoYxPuF6MLGrmSIYMCRvkl9I2g2NrXnLntUtdXPPkM/5Jqh82Bq0nUWH5cEo+
            5OCUVoLey85CrtZFDUXSRmIBCgFrNmqsej098xareiuXzMOLiSZQ8hGCMW/8UiRALuPEbw
            OfdYdnzVs6rkPY3PPGhrV6fbBRipbuuV2blsujlAv+gfBDb50QmHnPbZquXWquZI+xffxS
            PdP2yG1caFtKW6yIg4oALq8+cqFR7Hj1bjtHw3yR63Wx5+Lr7U5wgU8XN6TaI14gSMpfag
            ZvX8RS//TEah9Mt1yEOBk1uhJv5d44TN67l6GP0n6hBdNJ0l0nvSkKjgXd0wrpuquWM8vS
            rS0lcOGU33XpN6q8bFuCw6eVnDqbOKS/MeLndDmIsPHvh2OsVjIwoQYMqoaqB7WxbZAAAA
            wFPZO9aecDEYEvPyFGbamT8U/5G8EIcPRctIXceXKUmWa2PbMKcBxHAdu4KjXzT09JYd3y
            IEAMf1bEI8AcRfITI7d2G4VftjfeSssIz6B1RR70Z4sojSJ97LsO3Z1eBTxLH3CRfeIBLd
            dAawEnahrtsmCvtekMV/ooOiH0OJJFUC9TfY5eoibrpEeNdpz5GECuf61oipUusWoxQwq7
            6uosYw/QWjIqcBVW+/oEFP6XcnmKcftNNnf7+woPZ3XW8ytAAAAMEAy6BaUMUcgdZ79K5M
            qHsH/G+UVnW0ziZFVH/DxJqrgtQip0y31yH4PKRNP5zm2OcnOtMZAurCZMTSE34nKof1ol
            cMPPgd/WUKFnWR+Y0TDfTSNuEvJMmbLBoPAKqGd0XjMw0KgBZVFjb7F4cXFUNq0ag/IAB3
            91dVvUGdtBfYL/Y2pPs9madp4cxNBANTqB+9EZmCIiAhDZFJJKrbFM0l64iFIZBhraTD0m
            0PefjNKr8k/W6fheMX9ekvvXIRYh1dAAAAwQDBm9tpCtW6wOh4GBAicaa1+LnPvYA+9byH
            vq/y9LCZHKHtaXYecc4WMGFWE2rtQQ2qV6TDVVAPbsg8HCkgeZ/bcegqWVI2FkYHArt2VY
            SNpOBshk71yQ4jnByEVVznMTuhzAE5Y05YZ2AV+7aewZzHzb3xreYzSuEM5iRWWj1hPqp3
            0HREafUKdSzTzZ2riOazaX1+Dgf6RdjHMcdCcoVNHPaqpQxTbZknrs33mkzLvfPxqGTxRD
            ATTz3U3mYpnScAAAAYb3BlbmxhYnNAREVTS1RPUC1DTEhGMjMwAQID
            -----END OPENSSH PRIVATE KEY-----
          ignore-local-ssh-settings: true
        encrypt:
          enabled: false


jasypt:
  encryptor:
    bean: jasyptStringEncryptor





