server:
  port: 8081

spring:
  application:
    name: config-service
  kafka:
    bootstrap-servers: ${KAFKA_CLUSTER01:15.164.103.31:9092}

  cloud:
    bus:
      enabled: true

    config:
      server:
        git:
          uri: git@github.com:134talk/backend_config.git
          default-label: main
          private-key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAgEA535xJW4pI+nqMAv0y2/gw49QUCrmXugFEKg0nrhpFkditgEvADJw
            3/k5pO8DDEJGnx+aVA5fPlDDqBv0Ut0iWyYZFEg3E9KjhMkhq9HbPTXP9Pm4lj0d7EKr1f
            AcyrOnexRLzf4IqO9HoXbjAFwaDvUiDTo5WjwwXuWdmNu+acHp0E6W7fDpLR7sRTeHcrQ6
            oielD7vV7yGZArBeDGmQEw+SHr8np4mEPFoSSTp+4rS2xdNJ6nFE6xj+ZvJsyh2VPsSoEn
            6tfzeLNSWGdDJ+BqerxaOHZW+6K/qN2WkzmSHhJKZtKvcoR8khtDClR8rFJayDNY2oy1a8
            YBYH7kET0fs2H5wOZfO6LgacuWM/z4XmT1PoBdgshTiojQGvOlmtiACjdF7RsL6RygUxiI
            4rpZwufArA1RUmvTIjJUay12tjRgjO7GWmLqZ/oVlm8PMFmY3qXErVPB3C6jnObVUGXusr
            3QTNM4BVOytFLrY0fz8s7CiJMHTtH+E732foP9kIdXbTyfRqdykhWFTij5Y1xRBUHRyltH
            zDbPhlrglcdB1khJu8LeJLj1kovioti/9XdWv4ptYr1SS2x1lU0agiHClQ9wixHJFiczbk
            /IUwcIzAVUv3d6LClQQUrm0Bazes+44aiwF9jiVmYOAphtp3YjM+ykrBQeIJzFzEvpXT2J
            UAAAdItDHQRLQx0EQAAAAHc3NoLXJzYQAAAgEA535xJW4pI+nqMAv0y2/gw49QUCrmXugF
            EKg0nrhpFkditgEvADJw3/k5pO8DDEJGnx+aVA5fPlDDqBv0Ut0iWyYZFEg3E9KjhMkhq9
            HbPTXP9Pm4lj0d7EKr1fAcyrOnexRLzf4IqO9HoXbjAFwaDvUiDTo5WjwwXuWdmNu+acHp
            0E6W7fDpLR7sRTeHcrQ6oielD7vV7yGZArBeDGmQEw+SHr8np4mEPFoSSTp+4rS2xdNJ6n
            FE6xj+ZvJsyh2VPsSoEn6tfzeLNSWGdDJ+BqerxaOHZW+6K/qN2WkzmSHhJKZtKvcoR8kh
            tDClR8rFJayDNY2oy1a8YBYH7kET0fs2H5wOZfO6LgacuWM/z4XmT1PoBdgshTiojQGvOl
            mtiACjdF7RsL6RygUxiI4rpZwufArA1RUmvTIjJUay12tjRgjO7GWmLqZ/oVlm8PMFmY3q
            XErVPB3C6jnObVUGXusr3QTNM4BVOytFLrY0fz8s7CiJMHTtH+E732foP9kIdXbTyfRqdy
            khWFTij5Y1xRBUHRyltHzDbPhlrglcdB1khJu8LeJLj1kovioti/9XdWv4ptYr1SS2x1lU
            0agiHClQ9wixHJFiczbk/IUwcIzAVUv3d6LClQQUrm0Bazes+44aiwF9jiVmYOAphtp3Yj
            M+ykrBQeIJzFzEvpXT2JUAAAADAQABAAACAQC19DSK7yN3Dwz75unqXW2VSLgfyxh30Hbq
            uMtjVh+DW2jDFfsTdJIz+XjNovAKWq2XtQdguksyd9jR8ecAmr++VRuxTXG9KvtMC6tjmf
            dxDTL/oqjrre4vHdhit/BpgvxJSZKrvtifsDPlPcT/K2VwDE1PiEw8GMMMU/6jf1UTW0+k
            Y6FONOWSiZO8dAEKr47GldKvozxsUUQrUOUbbH3J/Zskf6tzjCtcJI/q7wd8uf5PT9vxYk
            aBY4vS7wmDc+0zAO/6WYeVTtskUvJzspxMLs5c8kQh/seeebm1AXOFEZQdcpKsCsimY/kR
            4IqI+2AqVIZtOYNLEEnQXICvTId+LfLv9e2EUOp69OzAcpMIsUcOpPQOIUA3prxQk7C8j6
            OzeQYGd/J4Zd1ZUNAoZ7EsL0Ic4PiLWF3jmshsSWRoaAGq2KRyB8ZpByB+dgN6qFr1xbcj
            deoy8r8jU3ywJeWJ2ucYNYwqdgGiJn+pJIQr6jUXHp10z5l/Yu80NZDmauAqw3xjXFUYCZ
            p3mfmrdylWAFub80gXH4BpXw0cAN2ob3vx4Kh2/DT+4hzBjjNqQZAmkKTpWzdSVH8HQC3p
            DgcCrZKoT39zmJ2n/joKhyOpZPzuTcqPkeJe1BgM3+BdFuL5sHoKTnTIFNd7IraMqS4sBo
            Lm5x5ts9m/TIAUOoXfoQAAAQA1dCbMrks/xP1bkapuQk3Yqp1CAvp4x5aNSiAmJzOik/lq
            hTVpiJ5N/Zc5QUrJmJiLd6otMqFCXuo4CsQR4GGtXkkaUeKHNYG96rcmNIdPc8ao8xHVZy
            5q3+cM9cErfN8uVbceY3173Fr9HKqBfY0LI0JP6U8dFdNPlbhZqUnM0qZiMjRa+EMAmOhe
            4BG/bJ17oBsLQKquRq6s7qGXjLHngFV7icQnzcOST79bvASic3d14lXydDPSyz85RTgbTC
            G4yt3HU68xtfZTtnvK3UBmzPapYxLqBPRE3VcSivsK4ofZxxQ8hXVnuHUdlu8E31AZUua0
            0vcTWnDBAsmz6sDeAAABAQD3BJYcNTvZSc1AsBZoLefzYu6+HGSLQkPNtFa/YaFFZYgxfG
            t2YnetB5pLhSlqup5XheQCDtDyrD1EcD5PjxrtLMRfgjnR4wCI4IloimA9413PJyRDpIoy
            T1Sy9l2gabOx0O9e/mtpdUFdkskHZpxNV6nUfjJgWyYPTFBLwDqjtTjT2eXOAgmR1RRzlZ
            A9oW4tmjp1KbHKk+Fw65IY22hFgy0dyu+Z5bREXk1oZSuSVotTdg1/viaerNhAwF1KGWz+
            tj7/thY+AkPs12cMmC45rdTuBAgSMD3OJWOwsP+Byqd5zWPeNwoBZvrLR0D8DZSrUmhk8L
            aXCcOqEzMVX7m7AAABAQDv6Vjzb8Ft0SELYe9b0qxuX+ntm1lQBj2RBatEFe+XFTaSZS27
            0lZUGvz2u98AAnFhIjE0hW0hW/IwWj9CHoTjyJoZ0Ua7t3zEy439LUUmGOZNbbvhHStvPO
            1CTTWU78ODidOz3Dg8L+NW+KagTldxXu76SXmAwmfjHj0lRnR4rohHBU6yeN222mSeTXy8
            3UToIAqTleGAF+KFk3/H+5K3N6YmTf/1kBAphrb+ggDSz6drB6h8E11Hkpo3muOhLzS6x3
            Tz/Vrj2Vz9yaJYwgCFsTKquALYUx9RpsTfJ9fa8B8a18Y0u88JPi0jOmEQfnN02FFPBt50
            bi/eOzjpe6nvAAAAEmR5ZGd1cy5rQGdtYWlsLmNvbQ==
            -----END OPENSSH PRIVATE KEY-----
          ignore-local-ssh-settings: true
        encrypt:
          enabled: false


jasypt:
  encryptor:
    bean: jasyptStringEncryptor





