server:
  port: 8081

spring:
  application:
    name: config-service
  kafka:
    bootstrap-servers: ${KAFKA_CLUSTER01:15.164.103.31:9092}

  cloud:
    bus:
      enabled: true

    config:
      server:
        git:
          uri: git@github.com:134talk/backend_config.git
          default-label: main
          private-key: ENC(8Kkdm/9b5uLQLbXQqo85YaAMwXQcQ2+lH7Lhog71nfSKV/D8xZI4w0fBBypDi3IW+y0ZoF7xvtOH/YRGnw1QU5rvHZlPKM4lWbMnrsLRxKJWU59lvYszjl5vZpMEw56Lis/USQhPzEpnitPn1D1iX6WuP6HrfpN1tNo80+y8qKoZsXmT9Rvr6GrE1eVDBiTyueeRcqgGND8Ch9jCw8N8gmW49tHVEFd/9rRIweLMW2nwRq9ZW4fF6M8ZBZNwTSJFNcAmYIKqT/4wDR1TeMUcMGwpQGbS4198nWT1UBPl3OExoNYeNZ1rpedAWdnf2zG7xZpTpy/nr4b+kA91otOIQxhl3/6+3uMCg5O11exuIgz0p8nZKFh2LXM5IoV8SOHb8NLi+o64G8M1A6V4Q0UfeSLj+xrQ5mvZ4DwHyLef1gaJzS8WFrYsIugGV9bXtYU6go3rXIzpT3dMQKtI7vFaQX2deexPXGzjTT9nLo9ZZgfxhLmChQWdmkJ3FAx53QvJYqQ6ggxJuin1fLuRXeFkBlXkyx9PKFzwmhZdU5O3eIBGoBJ3TQRfno7digfdVb1/A8dn9OQpViMHOcbqd23FoSyr+QuptckahYWBq0RTsp5PXtMUnQE2GrlQsl+/3mx8KkS7ATd0Wty11XyXcVivHc++4iPqw4DHJZxa74g/frDgwX/Eu/7bMhGx10xkyfxNyqstjkzm390LWicI0pcl6Ui0TUXsU6TQwMr08pQc6qOSRST18teRZdqHTi39wzZ2BM7MHebF/vaDVxCNMTVH3pxm2Z+7g3vYYuJK79UllwvhEYBDKfjil/X0Q3M3Mwl54RZjVN6QLmD+U0XuNEGPFs+1TlpYO1/m8tYj9wD9T3Btet2HM6qDLds8iKC6pcnp9KZcqjFkmWFbDY/AY+KwmT2r2eewT+s1FxndQHnsbIqeI9ZU0vRfRaSugYpF4NRmAar6zlZVNE2ePNecRzoQ/TKvln5i7x7guJkTEAee/yn7EmRTeQ05aOq4LL9+jMeLnVtEQV0wZTgmkb5KG9J/PFmEb9mx8y3HWh5I8no4bE8CHMpWW6fDOgzNMezQ6lOpjm+APUdA4/XaBvXDi9SiWsWlk4pmiSbJnHMooOo2kYsxvmMDSgpIC+jlfaoaQkVIYMswT3OGTkVmusHCC1wB/G//xvDigw2WXRjN4O3NTs8M7W4WZVyOLzfEu/Av7HhQYbQCXk/c46iOgovLxdAasBHLT7ZsAInq3ghrLL0SXnnu9cWYK4B46x5dRooJmi9raDsWk3iajXMSzjiwCZ+i2YUvezHRaWSUMedCmbHVlzkIIJJA6xypBA25OmzxkpajnuwepyEhVQaa1FFVfjNZGGqgj2XeTrpb5P6BiCgQMOFV4HKepfqq8Dn6+t93PUE83cdubHhi5YSY0KQkRpwuTSMRz3+vZ/n1T6KXFgz20KW0fwE93nYUEOX87rvESysjz99aU/nCvV8GIFQeqKm8kU1fWzeEiPEl6ucT35SGFGBuvLVw+WzshTVovsDnTny6BHUKmOKWkkRhrozbaj0YQU/aicyp1sbbS5tlDZGAlP/eB3WtEBEd+A7Dp+O1h9zne1bZ+20q1WQbGgeUyvv7e5v4VCxJxx4yRAszX8r24v9TQqLfVyST7vUN/EvMIlArZ+XhyrHiPBDmJCK2fXg3yisnA7mRpwbQIUmds+0p04p0ThDHJXedB+RJPqbGpIB2/f5HP06bOY5aBhp6zLpYmO6EUWI7194UKJ+7Shd2G2N1yw1pcZrWnYdrrKxe/Lr/oMD+7KVB6oSAs/eMwT7OXFaifK7Dj4raAXjoH3Epag4dp5qzYQQ7cbjMxCouMd1NA9yPaIAn0pFX5A4pcfmSKTYFgi8RET/UbnuObH+dVD3Pz7/0uNahM6CPJzDC/S2lGNR+LxU3vYPfBl/q1VlUfQY4tlj4K4rT1uuExQ4IXCyP4ZLrJGLjjlFCu0S+02kjjHi48np2UHbeaQX9ZIc+fbV7FoVpACjp6337We++oBrK85814vr/UCq/IH9NrGeIA2WuGH68KUKGMFiHWN/FKKqRPhByT8uMX4UF4ERZf7tGHUsmCAeyoPjeXB+q2l2Ye6biY2x97VSPObE5Ll6/hx3r+JfRkuMgr7qJUY280etCVJiikbwaifmRXx2IASoqRRilcWeyZfcnVlmVfme9w2Kk6W7dTAIT0EzPAI8LT54V2CsRAF4o6N+emLCJnxNIksiFBjeDUkz79jPq9qGlq8dwPFvuU04Kd+HfQlC3fbzSgsOzuWix+MYLUTIKW8oJ6F30J+nkYYYKuvJ3EzdcNeNMU5/9wpbAcZa0N3o8WtwYB5EWm0zJhyyodbV4NZ7O/ZjI9n6K45v0aXHx+VBXgrkfPu0h6FKSeO8BbOM2Icgh3sb5+yRaUq1x6Vr2J0f/Iimui+3uWL9tr0ChRAn6TvPB3ZIYUD1KsTpbOvc0cuyRcFzd69wyGtbiyZfN4TmeHsB5ElANs0LyYcRnHdePxQdICALlTDsWbGLh1+4iyyoFjdTrP7CU0OV0ith6PEtwx16+MMx2LC9qSbcy86MFfdV40KPxpu3AuCVgAU2e3pIxbFd7Md7nzQLRnhfjX32MOwvEcSk78aMy/TcmbgtxtrOiL5HFbRTE/24TbEPikedLaR24nUJ6ahuRezWMgu082Iw411dhJO3QZlhOJRdczDy8/fSvn6n99XHSlVmZXiTelCRYtNtISaRttwT5eQg3jgj0psfHwBOR0drg91sVhL9oj3TCu4UVRR6CNwEPdZmewOqzG+3GX12bsIsQ3vM7Z8UH7/GsilLBMYSttJwdmpDBmQl5elSF6cP4AVrtgROSq99djKtZA7DfgSoLec1GLBy0khlptm9ad7UOoGKE37dFKtcvKlHBRZ5FVYqan1/8dagqHz323FowC2Bt2+Wn5TuIef8d+4ztQeSQXTIm1OkxYWFs8s7FzzFa7r35HXj7ZxRdIUUYzUo/5yizgzLxh2lc4SgJFg6VCNWzl+F7kAdSv7x9NFxhDwReiWQuWfgDm6l+RCfhSfjU2EjxWa2J9KVaewRW3lWlHwcRs4xHRdYX9ZOly7vgIp2NwGI4tWsGH+Mtg1qVZ5B7TJhMxtvSkgwqE1pWuv9ikJbgTAEuJ9+yqKq4sWmEINMv/dTyzZ+3p9EgUJPwf98XNEsvtJ44J5BqN2CrYceaK/zWman+PCTy75LQ8vl1vJk4H8rw+5O21IYVGr+I/CgRQ9Rs42LScA9RXEnKbw4PmBvBXctT2qO3kj6UXwJuWJZx4hKi9FGR3blExhGw8Tz664MP/kUHFC7VffXDuwtxeIs2stbKAasB0eBxk4EWoJmJFwrk/x+Iqfv/lPWEOZqu08EgtIyJzqOM+9DPSem8HxzRtzlEgw0GsPQ+pDKQn15eWYWMZ13IMGY1i8IdYA==)
          ignore-local-ssh-settings: true
        encrypt:
          enabled: false


jasypt:
  encryptor:
    bean: jasyptStringEncryptor





