server:
  port: 8081

spring:
  application:
    name: config-service
  kafka:
    bootstrap-servers: ${KAFKA_CLUSTER01:15.164.103.31:9092}

  cloud:
    bus:
      enabled: true

    config:
      server:
        git:
          uri: git@github.com:134talk/backend_config.git
          default-label: main
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKAIBAAKCAgEA28eoZuaBMt/NLiRbNnZywjRRyqomE4iy7GNJIKzDN2/FkyE5
            ezbfsvx75gkgT191HIWKxwCSXnTa03KUiQcnJG57fd+vut1uHrJbZlACWLwu+DOs
            84vGQf25XJXXJEsm77lPQ/ns4NuZYZ1RkiPCmPV8Kya3fHM4M0CFeIx4XMgtvXCj
            PIxL6LW4NgLuRI/wJhr1G9kIH+p2f4COcIhgRAdyV7LFDf76IYkM0+0EonYPyIfi
            rFdqh6w+ya+XU/3xMn0YQVdSU07u03MgOjvoOxoZSbhEvORC2rp5xxkGZP3Ix1FE
            NmU59xofSdX8S0NHCoxA5hTlHw/Zbb6VwHR7InModdbg+Tq/VuS6d3B4eD3ksHco
            6gtwukIpZT09/L2o3oMMskku/V4kmjEyhSaYYenEpTVEdsPW4Rh+mHw/nySaz24e
            xXd+WRyqz2KcLVQSUTMzCU48BgUtQ6QTwvilHvZ+K7Qd6ORwZV6Eh70du5Td937d
            w73FrEHg4QUugx6+vPFxcDsxcuxgVrEWKP8EJH2ShLw49O+YSFavYTC7pSpynLvs
            eZiBhysDmbE4d1wB57RgZTz3N7SPaRwunkxjYSZ5Wa3brhw3pLKkN/74eHsABYFN
            1WZBJqoQF/svB4MQWScwLkLdhvmPpW63CprbCXSPwW2rDcVmxqBcGpZWFQUCAwEA
            AQKCAgBsrJ8ysov0MgHs7QFFPvCj4ucGxXeqdQ+0H6wLQiINiXEyvV0E9i9K+9nv
            91dIqDTqc4YZvMijeDi0EZYs46KROyhJJ5BnYBKRjzPutWVTp0m6ZSMCEn1oKCO+
            CkGlqpuIMiNlw3FEBpIjWHz7PD9/DvPlCnH0Uazaeu8EmsDxb/JeGBI/YEgwu5po
            6q4SrPHchbvplzmTPoZ1qYXFU0n2mZAKmVUjBI9+gZwcNrjx9Fr9l2OYQGlmyN8L
            L44udAUOKBkURi9pDkC9wdGPugutHcyfTUR/+oasTUTmFBO7YFolZKPMGeW9r+cE
            xZDJTm0UZCG7I13gLCAhSfoWfgJcLcdQaObv1vrbtI36f3z4L8FTU0FzHsOOeY6T
            X6mxeEH2Ba0/zrLK8zPm+3j0TDzEIKd5zegU8l7/79wLmOUvFiz2vX/MF/gzdPir
            TFGm/j/bPIDJpJJOiFz8LbTKpcgmH+WqnOhSO+tiPamD0Y5BAKTyMnMbGo3eIaBm
            CKVfRffrTOZ8BfuB4RsC4uxl8gUG+8TrcmB9FvDlcml2kBQPI0CIXtmKzOpJLZGP
            RUksrGP2wI2H5cl3MiBGqo4NwO9EzEEb6aGvnI9tcwfYMKpQQwjsrTRSVZRgMEdd
            PCqH+VWrCniqNSbCMIbJBRaQls4oU/uhbjxR93vC7LMkjeRWwQKCAQEA9b8CZny5
            fueHkpWaffoQ8NBkp32Lgum23VPHLTQHgLAr2Iz/PGG+fKQJP2Gwbwvf9U5pZSqn
            izOw49LNwLm924+c+RiW59feRCgdpVZTnei2kidOXr9mFJKZ5todcvFYxRzdWvZu
            2QpdfJwo1f6ezdAC97Tukk7bDnufA36d566ik7kQkQaM4iTE+VEWsLUD7MfRviH1
            yUn1lDmqG/jq3l9HMvVXJ3ShU2CQgABqQnWABp55zPvMCqjqA/O00hIo73MFw+6g
            1lvgE5dtQH/qTE4GzTaXc/I5bEjKLK5Z4PgDJnC25jqpmJILX5tlfZP3Q2egl/Ck
            d/boOs1cUf032QKCAQEA5PNI35QBT3fqwOa7H+fmTtIyt4mSMjWKgLZbzCfXfO65
            57I6/VxgYD1KT01ZVDVu9+zSRt3sJYlGTXHkEUriebCsnZPL4QgL7HbfxXsp3QnZ
            2yP7OpkmZ4wDOOmCLJYmmfFw9eTjcP4drXSESril4P9twzwgoY7b0nICwLVQtGAe
            HrKRZeK6NQrb+emPxEraePeDTJ0zxEEMcPlxrWUnOYN/gOR6YNTbKbm3qPHCYx80
            kCmn6mLeQtAB6IaOy+HZyOseocHAU8D83TH1aiEEw1wQQXkXmg/vjwX4AMdVLC+X
            BFY0T19r9agZJst3AB8e8O6TPYyHIjIe8zMw1kvXDQKCAQBSXONkEBdnlhfVJDj0
            UfSNkXq6vBQfG0/DnEmcN9zv35vCZ3c/+I6MXboPuSEWBsfYAqDGXGZs/DUkFkoJ
            dvdP+DEnN3uUVsBS3ZMaD/XUbeOK1ouoq8N9z6ivO5k1JfiXj9YMn52FNrkgg4IY
            Ps9gsX/dH5H6DV3T29Duregkd15b3mHUCXr8bFBsMyZEsVaQbGQ6sk0bWqNpO25t
            E588Snildp7wRWGwfSPREtKKVbFEBqdR8W5wgC52hp6q7ZU0s7tR8M+NKJvQVScz
            v+t6CYi0DMD0BlICnd7M3N6YzObZYluajDy9Ou1+7Kk2TnpH6Bpl8ixdXK52zs9L
            V2/5AoIBAQDLsx0iNyfXUaUfDeptX8FMXb5cB914KKTbEeSoxsX11Ny4pZ3QcBEb
            b0yfM/2Ha6cYlK8d+DMzzmgrXWqCbDMF/EgIR0g9JhCdycIcjRFZJXuceu36W+qM
            dEklqLR2AP3FN8i+LnChxqYW/rT5WkHT5s78xpFtzJIOMfv7AxcT9PS3cT7l/IyZ
            xtijCMgt6D9rIyTB1JgLQ6jTF0yp7nawuCuIPUAYySlZfXBHsxm1YT0+CqHoayC/
            JxybiqSgB4jiNzbgymbY3brc/qcQTuJTAqU/64IxQ35rrO7TmoZQMuNVK3GNMSP3
            xCDkoGB3TjkUOd/tAgv1Q8y/qssHzyA9AoIBAFbDL6EloM5IRSieU6AmaIUr3ov8
            kINaMTbJIg01qEQPKzHUE4p8waWasdoiG1Ac8bj3dAhAbTPj+hKbQK8z60m3UcGm
            OVTS4VC0gN9Zs9Uaf2W4UAp/8ysBiBJwRPplrPc1rBTwzfK2qmWnx6RsNB+D6fZj
            hyuWgK5jumduIpDLohCWti4nwb+CAmaOvGEKD+sxboKAGbLOiohcw/4XbbI7O372
            3Q9jhZPFl/w2IgUxGoiVLuTZzB+mGn1qDaaazWUmze4S4cYyviesgG3HypzJUCP2
            /sMz4WZJ9Z7fQu4ZUBqwC2njfJySWgLRsJ2krRl99h2wXhpytLoR6JHKmLk=
            -----END RSA PRIVATE KEY-----
          ignore-local-ssh-settings: true
        encrypt:
          enabled: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor





